2024-11-07 18:25:27,196:DEBUG:certbot._internal.main:certbot version: 2.11.0
2024-11-07 18:25:27,197:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2024-11-07 18:25:27,197:DEBUG:certbot._internal.main:Arguments: ['--standalone', '-d', 'easydeploy.com', '--config-dir', 'certbot/config', '--work-dir', 'certbot/work', '--logs-dir', 'certbot/logs']
2024-11-07 18:25:27,197:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2024-11-07 18:25:27,228:DEBUG:certbot._internal.log:Root logging level set at 30
2024-11-07 18:25:27,230:DEBUG:certbot._internal.plugins.selection:Requested authenticator standalone and installer None
2024-11-07 18:25:27,230:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * standalone
Description: Runs an HTTP server locally which serves the necessary validation files under the /.well-known/acme-challenge/ request path. Suitable if there is no HTTP server already running. HTTP challenge only (wildcards not supported).
Interfaces: Authenticator, Plugin
Entry point: EntryPoint(name='standalone', value='certbot._internal.plugins.standalone:Authenticator', group='certbot.plugins')
Initialized: <certbot._internal.plugins.standalone.Authenticator object at 0x10c3ee510>
Prep: True
2024-11-07 18:25:27,230:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.standalone.Authenticator object at 0x10c3ee510> and installer None
2024-11-07 18:25:27,231:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator standalone, Installer None
2024-11-07 18:25:27,318:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/2044441417', new_authzr_uri=None, terms_of_service=None), b4d4d954236fcb1d8df855480fc532e9, Meta(creation_dt=datetime.datetime(2024, 11, 7, 23, 19, 38, tzinfo=<UTC>), creation_host='1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa', register_to_eff='jitin@microgigs.ai'))>
2024-11-07 18:25:27,340:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2024-11-07 18:25:27,347:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2024-11-07 18:25:27,640:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/11" 200 746
2024-11-07 18:25:27,641:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Thu, 07 Nov 2024 23:25:27 GMT
Content-Type: application/json
Content-Length: 746
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.4-April-3-2024.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/draft-ietf-acme-ari-03/renewalInfo",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert",
  "zfI2XRymhqk": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417"
}
2024-11-07 18:25:27,642:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for easydeploy.com
2024-11-07 18:25:27,653:DEBUG:acme.client:Requesting fresh nonce
2024-11-07 18:25:27,653:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2024-11-07 18:25:27,742:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/11" 200 0
2024-11-07 18:25:27,743:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Thu, 07 Nov 2024 23:25:27 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: SHEOpopMGVHAQeeuAVf6hfIKOT-NU1gmMc2rNEfgSI_QV92A_Fw
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2024-11-07 18:25:27,743:DEBUG:acme.client:Storing nonce: SHEOpopMGVHAQeeuAVf6hfIKOT-NU1gmMc2rNEfgSI_QV92A_Fw
2024-11-07 18:25:27,743:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "easydeploy.com"\n    }\n  ]\n}'
2024-11-07 18:25:27,747:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjA0NDQ0MTQxNyIsICJub25jZSI6ICJTSEVPcG9wTUdWSEFRZWV1QVZmNmhmSUtPVC1OVTFnbU1jMnJORWZnU0lfUVY5MkFfRnciLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1vcmRlciJ9",
  "signature": "Pib4fFVgqnShIN_voWZFrEc5Trls9MnJeka7mK7UN1ZI9JUAaj1qnfQPrA-UrhXLNRCKb8uPOInpoVHXGw_RJQrNlljgmKT49nq18KPXUncoWWGadlHN61ceb_PqkMreoYB1afMYBj8wOEfrGIZEPWq3vrUwlekbOWwGkIzaKFeH3VkBioRtFovZ2nwbutC2h-HvIAieZfYx349aAlM73pdm60DnVhCyYOgJVXVATufypiZuf-nICvYghjSoS5GR-Dd8G0RXzei7ckeFhmTSQOJmrcAxTMdlpSW3D6QU8bCGWoiInwv2socuCwBll0r1iS8TC6U-21ml6GmwtRiw1Q",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogImVhc3lkZXBsb3kuY29tIgogICAgfQogIF0KfQ"
}
2024-11-07 18:25:27,868:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/11" 201 340
2024-11-07 18:25:27,869:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Thu, 07 Nov 2024 23:25:27 GMT
Content-Type: application/json
Content-Length: 340
Connection: keep-alive
Boulder-Requester: 2044441417
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/2044441417/320986467647
Replay-Nonce: SHEOpopMQEIc2qxt0RYdSFNQX1RLwrxPHYIOv4V5ie1IyoSaOJg
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2024-11-14T23:19:41Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "easydeploy.com"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/427024357287"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/2044441417/320986467647"
}
2024-11-07 18:25:27,870:DEBUG:acme.client:Storing nonce: SHEOpopMQEIc2qxt0RYdSFNQX1RLwrxPHYIOv4V5ie1IyoSaOJg
2024-11-07 18:25:27,870:DEBUG:acme.client:JWS payload:
b''
2024-11-07 18:25:27,873:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/427024357287:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjA0NDQ0MTQxNyIsICJub25jZSI6ICJTSEVPcG9wTVFFSWMycXh0MFJZZFNGTlFYMVJMd3J4UEhZSU92NFY1aWUxSXlvU2FPSmciLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LXYzLzQyNzAyNDM1NzI4NyJ9",
  "signature": "GNyIkZ6Do80pp6rt5L16X7Cwi5EdHJm9wUPB01BjMmGl_3F4VbD3vhq3G4Rkg6Mr2FF89C3sEs3n_qz_SofArEnOHEntOi8RRNUGg6Mdmi1KGK2Uwj84UQ2B1FiwvXAOyVfx14t2ifDO3FQRCx57YhY2X_NBaD4g2AxAHsky2r9HkzLJ-FwLmnqmFkc8-UNdubrZyE1Kv3zpDlUyCTLdbnRbOfNr-ljpGiaTGk6cZzXhjJRcvILLfu4YqdoXBxyrSYbGrtfhKo-IRNEda7veKfRHL90kGJOLQp0E-YFXifYS0vw1lwbli2Q2U9bGvcYGUzRGogZkKJ7KxHBPnxqR3g",
  "payload": ""
}
2024-11-07 18:25:27,971:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/427024357287 HTTP/11" 200 798
2024-11-07 18:25:27,972:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Thu, 07 Nov 2024 23:25:28 GMT
Content-Type: application/json
Content-Length: 798
Connection: keep-alive
Boulder-Requester: 2044441417
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: aHUr_lcVbH9JPnRsGWEjweoK2VIQupqFPSNyJEHDJ0ApTeDkkzM
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "easydeploy.com"
  },
  "status": "pending",
  "expires": "2024-11-14T23:19:41Z",
  "challenges": [
    {
      "type": "tls-alpn-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/427024357287/YUEh8g",
      "status": "pending",
      "token": "5gUQxHkzRg8sBcGOXcQjQXIzP9dIuTPjk2rw-hc6h9o"
    },
    {
      "type": "http-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/427024357287/e93RaA",
      "status": "pending",
      "token": "5gUQxHkzRg8sBcGOXcQjQXIzP9dIuTPjk2rw-hc6h9o"
    },
    {
      "type": "dns-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/427024357287/PorTbA",
      "status": "pending",
      "token": "5gUQxHkzRg8sBcGOXcQjQXIzP9dIuTPjk2rw-hc6h9o"
    }
  ]
}
2024-11-07 18:25:27,972:DEBUG:acme.client:Storing nonce: aHUr_lcVbH9JPnRsGWEjweoK2VIQupqFPSNyJEHDJ0ApTeDkkzM
2024-11-07 18:25:27,974:INFO:certbot._internal.auth_handler:Performing the following challenges:
2024-11-07 18:25:27,974:INFO:certbot._internal.auth_handler:http-01 challenge for easydeploy.com
2024-11-07 18:25:28,111:DEBUG:acme.standalone:Successfully bound to :80 using IPv6
2024-11-07 18:25:28,111:DEBUG:acme.standalone:Certbot wasn't able to bind to :80 using IPv4, this is often expected due to the dual stack nature of IPv6 socket implementations.
2024-11-07 18:25:28,115:DEBUG:acme.client:JWS payload:
b'{}'
2024-11-07 18:25:28,118:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/chall-v3/427024357287/e93RaA:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjA0NDQ0MTQxNyIsICJub25jZSI6ICJhSFVyX2xjVmJIOUpQblJzR1dFandlb0syVklRdXBxRlBTTnlKRUhESjBBcFRlRGtrek0iLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2NoYWxsLXYzLzQyNzAyNDM1NzI4Ny9lOTNSYUEifQ",
  "signature": "Be1hkF4UBVoyk3LM8h9FxWrYNymvc9KLIP1StKyuAA-MtFvi-lOYe8DX77Rr2ultzqv9bpz8FOERLXV7g0NoNniOgQqtaqO08cCGPEAJ2WsluoF-TBZEQOkJb3LNS8KBAjLubBlngHwYg1o8vtTux76isGZ-bAxckUG476kpuE8PNQctIPtCWo6sNaG_cg46JiMtW6CBDJr5JjBT2HVGqV1F6Tjw13_DsZIjpdwimie94Esl3FIu0FwW5fR_yMu1rfVQd3cFSb3CMc4ZLHEnz-MTz6_ZdVRunFGm-UsTFW9nRNmwwhLZdDy568HhKTQrXG_wEuxu4jbxblJcJ5sIpQ",
  "payload": "e30"
}
2024-11-07 18:25:28,219:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/chall-v3/427024357287/e93RaA HTTP/11" 200 187
2024-11-07 18:25:28,220:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Thu, 07 Nov 2024 23:25:28 GMT
Content-Type: application/json
Content-Length: 187
Connection: keep-alive
Boulder-Requester: 2044441417
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-v02.api.letsencrypt.org/acme/authz-v3/427024357287>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/chall-v3/427024357287/e93RaA
Replay-Nonce: aHUr_lcVzw9wcbERR55Sq08emFaDgKrxV4GRfT4jqxCIFqV7GkA
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "type": "http-01",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/427024357287/e93RaA",
  "status": "pending",
  "token": "5gUQxHkzRg8sBcGOXcQjQXIzP9dIuTPjk2rw-hc6h9o"
}
2024-11-07 18:25:28,220:DEBUG:acme.client:Storing nonce: aHUr_lcVzw9wcbERR55Sq08emFaDgKrxV4GRfT4jqxCIFqV7GkA
2024-11-07 18:25:28,221:INFO:certbot._internal.auth_handler:Waiting for verification...
2024-11-07 18:25:29,228:DEBUG:acme.client:JWS payload:
b''
2024-11-07 18:25:29,232:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/427024357287:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjA0NDQ0MTQxNyIsICJub25jZSI6ICJhSFVyX2xjVnp3OXdjYkVSUjU1U3EwOGVtRmFEZ0tyeFY0R1JmVDRqcXhDSUZxVjdHa0EiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LXYzLzQyNzAyNDM1NzI4NyJ9",
  "signature": "N9sCusxA_gNhvU4Li1LZf1FnTT1OjnJ9M5khl7EvUAS6qF_NrpDnmrD_nyMP_CyOkGrXH7zueBp-CEi7qoc98lHj1wRpGbQoahIDY6JQY2CQzImmQ5zxy5lPtjGgfnnQtEvKetzpBlrvodIjMECwvy6ugKO1nPznd0TPWkFChA-_G0NlHsli-jHfSi5aSnCCEL4oAGNFAeCg5JvsJa1C2lhuTzXWckkVAHrFWe98vaeRU5tSRCNK52_PXnpC2FJAvXawZQu-6kVcRCqDyOer2n9GpTJFTOOwSIBA33_Am9daGc7-LJcJE1vaC5DZdZKLKz1uvzmivo07j9pGdzb6Yg",
  "payload": ""
}
2024-11-07 18:25:29,404:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/427024357287 HTTP/11" 200 1030
2024-11-07 18:25:29,405:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Thu, 07 Nov 2024 23:25:29 GMT
Content-Type: application/json
Content-Length: 1030
Connection: keep-alive
Boulder-Requester: 2044441417
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: aHUr_lcVw1MZj-wDGeWENkxgUyFkoesnEIQqP__sHkmIn6jOjuA
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "easydeploy.com"
  },
  "status": "invalid",
  "expires": "2024-11-14T23:19:41Z",
  "challenges": [
    {
      "type": "http-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/427024357287/e93RaA",
      "status": "invalid",
      "validated": "2024-11-07T23:25:28Z",
      "error": {
        "type": "urn:ietf:params:acme:error:unauthorized",
        "detail": "157.230.161.221: Invalid response from http://easydeploy.com/.well-known/acme-challenge/5gUQxHkzRg8sBcGOXcQjQXIzP9dIuTPjk2rw-hc6h9o: 404",
        "status": 403
      },
      "token": "5gUQxHkzRg8sBcGOXcQjQXIzP9dIuTPjk2rw-hc6h9o",
      "validationRecord": [
        {
          "url": "http://easydeploy.com/.well-known/acme-challenge/5gUQxHkzRg8sBcGOXcQjQXIzP9dIuTPjk2rw-hc6h9o",
          "hostname": "easydeploy.com",
          "port": "80",
          "addressesResolved": [
            "157.230.161.221"
          ],
          "addressUsed": "157.230.161.221"
        }
      ]
    }
  ]
}
2024-11-07 18:25:29,405:DEBUG:acme.client:Storing nonce: aHUr_lcVw1MZj-wDGeWENkxgUyFkoesnEIQqP__sHkmIn6jOjuA
2024-11-07 18:25:29,406:INFO:certbot._internal.auth_handler:Challenge failed for domain easydeploy.com
2024-11-07 18:25:29,406:INFO:certbot._internal.auth_handler:http-01 challenge for easydeploy.com
2024-11-07 18:25:29,407:DEBUG:certbot._internal.display.obj:Notifying user: 
Certbot failed to authenticate some domains (authenticator: standalone). The Certificate Authority reported these problems:
  Domain: easydeploy.com
  Type:   unauthorized
  Detail: 157.230.161.221: Invalid response from http://easydeploy.com/.well-known/acme-challenge/5gUQxHkzRg8sBcGOXcQjQXIzP9dIuTPjk2rw-hc6h9o: 404

Hint: The Certificate Authority failed to download the challenge files from the temporary standalone webserver started by Certbot on port 80. Ensure that the listed domains point to this machine and that it can accept inbound connections from the internet.

2024-11-07 18:25:29,413:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/local/Cellar/certbot/2.11.0_2/libexec/lib/python3.13/site-packages/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/certbot/2.11.0_2/libexec/lib/python3.13/site-packages/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2024-11-07 18:25:29,414:DEBUG:certbot._internal.error_handler:Calling registered functions
2024-11-07 18:25:29,414:INFO:certbot._internal.auth_handler:Cleaning up challenges
2024-11-07 18:25:29,414:DEBUG:certbot._internal.plugins.standalone:Stopping server at :::80...
2024-11-07 18:25:29,617:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/usr/local/Cellar/certbot/2.11.0_2/libexec/lib/python3.13/site-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/Cellar/certbot/2.11.0_2/libexec/lib/python3.13/site-packages/certbot/_internal/main.py", line 1894, in main
    return config.func(config, plugins)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/certbot/2.11.0_2/libexec/lib/python3.13/site-packages/certbot/_internal/main.py", line 1600, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/local/Cellar/certbot/2.11.0_2/libexec/lib/python3.13/site-packages/certbot/_internal/main.py", line 143, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/local/Cellar/certbot/2.11.0_2/libexec/lib/python3.13/site-packages/certbot/_internal/client.py", line 517, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
                          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/local/Cellar/certbot/2.11.0_2/libexec/lib/python3.13/site-packages/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/local/Cellar/certbot/2.11.0_2/libexec/lib/python3.13/site-packages/certbot/_internal/client.py", line 496, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
  File "/usr/local/Cellar/certbot/2.11.0_2/libexec/lib/python3.13/site-packages/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/certbot/2.11.0_2/libexec/lib/python3.13/site-packages/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
2024-11-07 18:25:29,623:ERROR:certbot._internal.log:Some challenges have failed.
